on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: echo "docker login"

  create-DockerImage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Docker Image
        run: echo "build docker images"


  deployment:
    needs: create-DockerImage
    runs-on: ubuntu-latest
    steps:
      - name: Aws Login
        run: echo "aws login"
