on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: echo "docker login"


  deployment:
     runs-on: ubuntu-latest
     steps:
       - name: Aws Login
         run: echo "aws login"
